"""
pretrain_bc.py — Behavioural Cloning pretraining for OrbitalInsertionEnv.

Trains a policy network to imitate the periapsis expert controller using
supervised learning on the demonstration dataset generated by generate_demos.py.

The BC-pretrained policy is saved as an SB3-compatible model that can be
directly loaded into SAC for fine-tuning. This warm start means SAC sees
successful episodes from step 1, giving it the sparse reward signal needed
to improve beyond the expert.

Training details
----------------
  Network:    2-layer MLP, 256 hidden units (matches SAC default)
  Loss:       MSE on action (continuous action space)
  Optimiser:  Adam, lr=1e-3 with cosine annealing
  Epochs:     50 (configurable)
  Batch size: 512

Usage
-----
    # Train BC from demos, save pretrained model
    python scripts/pretrain_bc.py --demos demos/demos_200.npz --out bc_model/

    # Then fine-tune with SAC
    python scripts/train_sac.py --mode fixed --planet earth --steps 200000 \\
                        --pretrain bc_model/bc_policy.zip --tag bc_finetune
"""

import argparse
import os
import sys
import time
from pathlib import Path

import numpy as np

parser = argparse.ArgumentParser(description="Behavioural cloning pretraining")
parser.add_argument(
    "--demos", required=True, help="Path to .npz demo file from generate_demos.py"
)
parser.add_argument(
    "--out", default="bc_model/", help="Output directory for pretrained model"
)
parser.add_argument("--epochs", type=int, default=50)
parser.add_argument("--batch-size", type=int, default=512)
parser.add_argument("--lr", type=float, default=1e-3)
parser.add_argument("--hidden", type=int, default=256)
parser.add_argument(
    "--val-frac",
    type=float,
    default=0.1,
    help="Fraction of data held out for validation",
)
parser.add_argument("--seed", type=int, default=42)
parser.add_argument("--obs-dim", type=int, default=18)
args = parser.parse_args()

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, random_split

import planet_rl.core.planet_io

Path(args.out).mkdir(parents=True, exist_ok=True)
torch.manual_seed(args.seed)
np.random.seed(args.seed)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ── Load dataset ───────────────────────────────────────────────────────────────

print(f"Loading demonstrations: {args.demos}")
data = np.load(args.demos, allow_pickle=True)
obs_all = torch.tensor(data["observations"], dtype=torch.float32)
act_all = torch.tensor(data["actions"], dtype=torch.float32)
N = len(obs_all)

print(f"  {N:,} (obs, action) pairs")
print(f"  obs:  {obs_all.shape}  range [{obs_all.min():.2f}, {obs_all.max():.2f}]")
print(f"  act:  {act_all.shape}  unique rows: {len(torch.unique(act_all, dim=0))}")
print(f"  device: {device}\n")

# Train / validation split
n_val = max(1, int(N * args.val_frac))
n_train = N - n_val
dataset = TensorDataset(obs_all, act_all)
train_ds, val_ds = random_split(
    dataset, [n_train, n_val], generator=torch.Generator().manual_seed(args.seed)
)
train_loader = DataLoader(
    train_ds, batch_size=args.batch_size, shuffle=True, drop_last=True
)
val_loader = DataLoader(
    val_ds, batch_size=args.batch_size, shuffle=False, drop_last=False
)

print(f"  Train: {n_train:,}  Val: {n_val:,}  Batches/epoch: {len(train_loader)}\n")

# ── Policy network (matches SB3 SAC MlpPolicy architecture) ───────────────────


class BCPolicy(nn.Module):
    """
    2-layer MLP matching the SAC MlpPolicy default architecture.
    Input:  obs (18,)
    Output: action (3,) in [-1, 1]
    """

    def __init__(self, obs_dim: int, act_dim: int, hidden: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(obs_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
            nn.Linear(hidden, act_dim),
            nn.Tanh(),  # output in [-1, 1]  (matches action space)
        )

    def forward(self, x):
        return self.net(x)


obs_dim = obs_all.shape[1]
act_dim = act_all.shape[1]
policy = BCPolicy(obs_dim, act_dim, args.hidden).to(device)
n_params = sum(p.numel() for p in policy.parameters())
print(
    f"Policy:  {obs_dim}→{args.hidden}→{args.hidden}→{act_dim}  ({n_params:,} params)"
)

# ── Training ───────────────────────────────────────────────────────────────────

criterion = nn.MSELoss()
optimiser = optim.Adam(policy.parameters(), lr=args.lr)
scheduler = optim.lr_scheduler.CosineAnnealingLR(
    optimiser, T_max=args.epochs, eta_min=1e-5
)

best_val_loss = float("inf")
best_epoch = 0
history = []

print(f"\nTraining BC ({args.epochs} epochs, batch={args.batch_size}, lr={args.lr})\n")
print(
    f"  {'epoch':>6}  {'train_loss':>12}  {'val_loss':>10}  {'act_err':>9}  {'lr':>8}"
)
print("  " + "─" * 55)

t_start = time.time()

for epoch in range(1, args.epochs + 1):
    # ── Train ────────────────────────────────────────────────────────────────
    policy.train()
    train_loss = 0.0
    for obs_b, act_b in train_loader:
        obs_b = obs_b.to(device)
        act_b = act_b.to(device)
        pred = policy(obs_b)
        loss = criterion(pred, act_b)
        optimiser.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(policy.parameters(), 1.0)
        optimiser.step()
        train_loss += loss.item()
    train_loss /= len(train_loader)

    # ── Validate ─────────────────────────────────────────────────────────────
    policy.eval()
    val_loss = 0.0
    act_errs = []
    with torch.no_grad():
        for obs_b, act_b in val_loader:
            obs_b = obs_b.to(device)
            act_b = act_b.to(device)
            pred = policy(obs_b)
            val_loss += criterion(pred, act_b).item()
            act_errs.append((pred - act_b).abs().mean().item())
    val_loss /= len(val_loader)
    mean_act_err = np.mean(act_errs)

    scheduler.step()
    lr_now = scheduler.get_last_lr()[0]

    history.append(
        {"epoch": epoch, "train": train_loss, "val": val_loss, "act_err": mean_act_err}
    )

    # Save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_epoch = epoch
        torch.save(policy.state_dict(), os.path.join(args.out, "bc_policy_best.pt"))

    if epoch % 5 == 0 or epoch == 1 or epoch == args.epochs:
        elapsed = time.time() - t_start
        print(
            f"  {epoch:6d}  {train_loss:12.6f}  {val_loss:10.6f}  "
            f"{mean_act_err:9.4f}  {lr_now:8.2e}  "
            f"{'★' if epoch == best_epoch else ''}"
        )

print(f"\n  Best val loss: {best_val_loss:.6f} at epoch {best_epoch}")
print(f"  Total time:   {time.time() - t_start:.0f}s")

# Save final model too
torch.save(policy.state_dict(), os.path.join(args.out, "bc_policy_final.pt"))

# ── Evaluate on environment ────────────────────────────────────────────────────

print("\nEvaluating BC policy on environment (20 episodes)...")
from planet_rl.core.env import OrbitalInsertionEnv

policy.eval()
policy.cpu()


def bc_action(obs_np: np.ndarray) -> np.ndarray:
    with torch.no_grad():
        t = torch.tensor(obs_np, dtype=torch.float32).unsqueeze(0)
        return policy(t).squeeze(0).numpy()


successes_eval = 0
rewards_eval = []

for ep in range(20):
    preset = ["earth", "mars", "venus", "moon", "titan"][ep % 5]
    env = OrbitalInsertionEnv(
        obs_dim=args.obs_dim,
        planet_preset=preset,
        randomize_planet=False,
        initial_altitude=0,
    )
    obs, _ = env.reset()
    done = trunc = False
    ep_r = 0.0

    while not (done or trunc):
        action = np.clip(bc_action(obs), -1, 1)
        obs, r, done, trunc, info = env.step(action)
        ep_r += r

    if info["success"]:
        successes_eval += 1
    rewards_eval.append(ep_r)

print(f"  Success rate: {successes_eval}/20 = {successes_eval / 20 * 100:.0f}%")
print(f"  Mean reward:  {np.mean(rewards_eval):.1f}")

# ── Save SB3-compatible model ──────────────────────────────────────────────────

print("\nSaving SB3-compatible pretrained model...")

from stable_baselines3 import SAC

from planet_rl.core.env import OrbitalInsertionEnv

env_for_sac = OrbitalInsertionEnv(
    obs_dim=args.obs_dim,
    planet_preset="earth",
    randomize_planet=False,
    initial_altitude=0,
)

# Create a SAC model and overwrite its actor weights with our BC weights
sac_model = SAC(
    "MlpPolicy",
    env_for_sac,
    policy_kwargs=dict(net_arch=[args.hidden, args.hidden]),
    verbose=0,
)

# Map BC weights → SB3 actor network weights
# SB3 SAC actor: policy.actor.latent_pi (MLP) + policy.actor.mu (mean head)
# BCPolicy:      net[0..4]  (Linear, ReLU, Linear, ReLU, Linear, Tanh)
bc_state = policy.state_dict()
actor = sac_model.policy.actor

try:
    with torch.no_grad():
        actor.latent_pi[0].weight.copy_(bc_state["net.0.weight"])
        actor.latent_pi[0].bias.copy_(bc_state["net.0.bias"])
        actor.latent_pi[2].weight.copy_(bc_state["net.2.weight"])
        actor.latent_pi[2].bias.copy_(bc_state["net.2.bias"])
        actor.mu.weight.copy_(bc_state["net.4.weight"])
        actor.mu.bias.copy_(bc_state["net.4.bias"])
    print("  ✓ Weights transferred to SAC actor")
except Exception as e:
    print(f"  ✗ Weight transfer failed: {e}")
    print("    Saving BC weights separately — load manually")

sac_path = os.path.join(args.out, "bc_policy.zip")
sac_model.save(sac_path)
print(f"  Saved SB3 model: {sac_path}")

# ── Save training history ──────────────────────────────────────────────────────

import json

history_path = os.path.join(args.out, "bc_history.json")
with open(history_path, "w") as f:
    json.dump(history, f, indent=2)

print(f"\nAll outputs in {args.out}/")
print("  bc_policy_best.pt  — best checkpoint (raw weights)")
print("  bc_policy_final.pt — final checkpoint (raw weights)")
print("  bc_policy.zip      — SB3-compatible model for fine-tuning")
print("  bc_history.json    — training curves")
print(f"\nTo fine-tune with SAC:")
print(f"  python train_sac.py --mode fixed --planet earth --steps 200000 \\")
print(f"    --pretrain {sac_path} --tag bc_finetune_earth")
